### PR TITLE
French & Turkish translations for sayswho

### PR DESCRIPTION
**Pull request by cardpuncher**
I'll send fixes for the installer this evening or tomorrow at worst.

### CODE REVIEW

**Comment by shidel** [comment]
> I'll send fixes for the installer this evening or tomorrow at worst.

Installer fixes?

Oh, did you notice BLOCEK shows missing keys?

**Comment by shidel** [comment]
I just checked the SaysWho. French is good. But Turkish, the Hint is a hair too wide. Like about 1 pixel too wide. Exactly one letter gets cropped off.
Screen Shot 2022-02-16 at 3 00 17 AM
If it were using a monospace font, it would be limited to 40 characters. But, it doesn't and only the one letter got lost in the 54 character translation. I don't know if it's possible to restructure or reword translation to be narrower. (For example "iiii" is a lot narrower than "zzzz")

This brings up an additional questions regarding the Turkish Font. To my eye, I think the C looking character should be a little lower. And the S looking one is basically looks like an S with a tail and should be as tall as the U. I ask so I can update the font to make them look nicer.

**Comment by shidel** [comment]
No need to update HINT string for SaysWho. I made it alternate between before and after the comma at startup so entire message is now shown.

**Comment by cardpuncher** [comment]
On 16.02.2022 11:19, shidel wrote:

> This brings up an additional questions regarding the Turkish Font. To my 
> eye, I think the C looking character should be a little lower. And the S 
> looking one is basically looks like an S with a tail and should be as 
> tall as the U. I ask so I can update the font to make them look nicer.

Sorry for the delay. I gave BlockDrop and SaysWho a try with the latest 
build and the fonts look nice.

**Comment by shidel** [comment]
No problem, ok thanks for the feedback.

**Pull request merged**
