### PR TITLE
Various corrections in French and Turkish after playing with RC5

### PR DESCRIPTION
**Pull request by cardpuncher**
Also, Jerome, please include the latest cdrom.tr file in the next release as I think the /p added to the end of the CD.ERROR item in 164dc29 prevents the prompt from turning red until a CLS is issued as it currently happens in RC5. Funny, but annoying too :)

### CODE REVIEW

**Comment by shidel** [comment]
> Also, Jerome, please include the latest cdrom.tr file in the next release as I think the /p added to the end of the CD.ERROR item in [164dc29](https://github.com/shidel/fd-nls/commit/164dc291b127524bc84cce40b2f64c137b19cf0e) prevents the prompt from turning red until a CLS is issued as it currently happens in RC5. Funny, but annoying too :)

Some times there are some parameters given to vecho before the NLS text is parsed. Sometimes there is a /n that tells it to not perform a CRLF after outputting the text. So, what happens is the last color actually used gets continued. So, even though it ended in /fGrey no further text is displayed and no CRLF was performed. That leaves the last color real color as red. Then DOS just keeps using it. I should check to see it happens in other languages and if anything needs adjusted. 

If the /p makes things look off, you can just tell it to print a space character using /c32 or " ". Or, a /e to clear the rest of the line. That would cause a character using /fGray to be written and would be seen by future vecho commands and by DOS.

**Comment by shidel** [comment]
Looks good. :-)

**Comment by cardpuncher** [comment]
Running CDROM.BAT was spilling red color. Then I added a /p and everything was OK. I removed it again to see if that was the origin of the problem, and now the prompt is in yellow as shown below. Hope this will be useful in some way :-)


colored_prompt

**Comment by shidel** [comment]
It is that DOS issue thing regarding screen scrolling and last color. 

However, I just checked... I have /p in the English version. So, the /p is needed to do a CRLF and prevent the color issue. Probably a /n before the NLS lookup that turns off automatic CRLF. So, leave the /P in there. :-)

To see what I mean, check out these images.
Screen Shot 2021-12-10 at 10 26 53 AM
Screen Shot 2021-12-10 at 10 28 11 AM

On a side note, if you like White on Blue in DOS, you can do a vcls /g /fWhite /bBlue. But, many programs ignore the current color attribute state and just set it to 0x07 (Light Gray on Black).

**Pull request merged**
