### PR TITLE
WIP: Add/Improve Turkish translations

### PR DESCRIPTION
**Pull request by bitigchi**

### CODE REVIEW

**Comment by bitigchi** [comment]
I'm installing RC3 now, I will update the translations as I test.

**Comment by bitigchi** [comment]
I presume below image is PARTING, but for some reason it's not displaying:

VirtualBox_FreeDOS_01_06_2020_02_17_12

**Comment by bitigchi** [comment]
It looks like the utilities are not updated to use the current translations.

**Comment by shidel** [comment]
> I presume below image is PARTING, but for some reason it's not displaying:
> 
> VirtualBox_FreeDOS_01_06_2020_02_17_12

This type of issue would be caused by the "[window frame](https://github.com/shidel/fd-nls/blob/2542ff995c622b78a26db1bf56b68bb0dd005e70/fdi/language/tr/FDSETUP.DEF#L57)" not being adjusted for the different text. 

With several dozen possible screens that can appear in the installer and being unable to read the language translations, there is not a practical way for me to reliably detect such issues. 

This is what i recommend. Using the LiveCD and VirtualBox. Boot the VM using the Live Environment. Once at the command line. Issue a **set LANG=** to clear the default EN language. Run **setup** and walk through an install. When you see an issue, exit the installer. run  **edit F:\FREEDOS\SETUP\%LANG%\FDSETUP.DEF** and update the correct frame width and/or height and message if needed. Mirror your changes to the sources in an editor on your actual machine. The run setup again. Repeat until everything looks good. Then go through the same process running "setup adv" to handle all of the advanced mode screens. 

It is a bit of a pain. But, at present there is no better process available to ensure the messages are all displayed correctly.

**Comment by shidel** [comment]
> It looks like the utilities are not updated to use the current translations.

Your updates should make the next release. Probably 1.3-Final.

**Comment by bitigchi** [comment]
> > It looks like the utilities are not updated to use the current translations.
> 
> Your updates should make the next release. Probably 1.3-Final.

Is there a list of improvements made for this RC? Both FreeCOM and Kernel on Github do not have any new commits since the last RC. That said, I'd personally prefer another RC before the final, since testing changes on a final release does not sound very sensible. :)

**Comment by shidel** [comment]
I don't usually keep "Change Logs" although I may start including it for the installer. From RC2 to RC3 the Kernel was not updated. We did start including both the COMMAND (Main FreeCOM package) and now a FREECOM package. The FREECOM is the new beta command.com and is not installed by default. Also, the addition of the Floppy Diskette Edition. Some major changes to V8Power Tools (Powers the UI and Logic of the Installer) to better support multi-language text and some additional features. Updates to the Installer to use the improved multilang text support in V8PT (basically, that was a simple search and then replace a couple hundred lines with cleanup). Some redesigned hard disk detection and state logic to improve overall compatibility. Some compatibility, general improvements and visual polishing to the LiveCD. Couple minor bug fixes to the main Release Build Environment. Some other miscellaneous improvements. Then, there are also a couple new and a few updated packages.

**Comment by shidel** [comment]
To your second point -- another RC before final. That depends. If all that is updated for the installer is some language text there is not really much point. That does not effect the overall functionality of the installer or installed OS. Nor does it effect compatibility in any way. Another factor, involves what (if any) packages are updated. If Floppy Birds goes to version 1.1, that won't cause a new Release Candidate. But on the other hand, if we get a kernel update...

**Comment by shidel** [comment]
Oh, on a side note... I see you made a translation for FDI-x86 (The Floppy Edition Installer). Thank you. I wanted to mention that I just added 3 additional files I originally forgot. The new files contain generic notes, facts and hints to the user at intervals while the OS is installing.  Also, you may want to consider doing one for SLICER. It is an 8086 compatible file archiver and spanning  (not compression, like zip and such) that supports groupings, tags embedded multi-lang messages and etc. It handles the package installation for the Floppy Edition.

**Comment by bitigchi** [comment]
@shidel, thank you for the change logs, I appreciate it.

Wait -- so the included shell in RC3 isn't FreeCOM? No wonder I cannot see Turkish localisations with it; how to enable it? I couldn't see it in FDIMPLES. I'd consider this a blocker, because in status quo, FreeDOS is not Turkish at all without the shell localisation. We could just scrap the whole Turkish entry in the installer if this is not fixed, because it does not make sense to ship it without shell localisation support. I already opened an issue [here](https://github.com/FDOS/freecom/issues/24).

Question about the x86 installer -- will it support selecting keyboard layouts? Or is it supposed to be a single layout?

Also, why the full installer is included with the Floppy version? Isn't it just supposed to boot the system? It cannot find the packages to install anyway (or I am doing something wrong).

I will translate the additional bits ASAP, in the meantime, where are the strings for the additional keyboard layouts stored? I cannot seem to find them, I need to modify Swiss French and Swiss German.

Regarding the another RC thing, I asked because I was naturally expecting to test the overhauled strings, which is also important in itself, since it can lead to misleading prompts and info from the user's perspective. And there's this problem with the Turkish FreeCOM (command.com) localisation issue, if there is no RC before the final, we'll never know if it's fixed or not. And FreeCOM repo doesn't seem to be active at all, no new code is being added, which leads to the question if the Github repo is the source for the latest RC? Anyway, sorry for the rant but I really hope we can confirm and validate this issue; otherwise I'd prefer Turkish language option totally removed until it's fixed (It would really suck to see all the community's work go in drain, my and @cardpuncher's especially).

**Comment by cardpuncher** [comment]
On 2.06.2020 14:11, Emir Sarı wrote:
> @shidel <https://github.com/shidel>, thank you for the change logs, I
> appreciate it.
> 
> Wait -- so the included shell in RC3 isn't FreeCOM? No wonder I cannot
> see Turkish localisations with it; how to enable it? I couldn't see it
> in FDIMPLES. I'd consider this a blocker, because in status quo, FreeDOS
> is not Turkish at all without the shell localisation. We could just
> scrap the whole Turkish entry in the installer if this is not fixed,
> because it does not make sense to ship it without shell localisation
> support. I already opened an issue here> <https://github.com/FDOS/freecom/issues/24>.

On this bug report, @PerditionC says that in a few weeks he plans to
release a new version of FreeCOM, see
<https://github.com/FDOS/freecom/issues/24#issuecomment-629821438>. The
Turkish (and hopefully improved French) strings will then be included.

There is also a full Spanish translation of everything on freedoslocal
*and* of the HTML help files on
<https://sourceforge.net/p/freedos/bugs/280/>, and a full French
translation of the HTML Help files from yours truly (see
<https://sourceforge.net/p/freedos/mailman/message/37022572/>). A
version upgrade of the HTML Help will probably be required, as well as
some work on it (see the previous message). As nobody replied, I'm
planning to ping the list again in a couple of days. Minicom and FDTUI
should see new releases fairly soon, with new translations too.

Therefore IMHO it would make sense to wait a bit (like a few weeks, for
FreeCOM at least and maybe the kernel too) and then release another RC
-- I concur with Emir on this one.

> I will translate the additional bits ASAP, in the meantime,(...)

Hm, looks like more work :-P So I'm going to do the French versions of
these files but couldn't find the built-in English strings for pgme.
Would it be possible to add them as well, like the Spanish version, so
we can translate?

Last but not least, thanks for all your hard work Jerome.

**Comment by shidel** [comment]
The Shell is FreeCOM, but it is an older “stable” version. The beta FreeCOM is being updated by a new developer and will most likely eventually replace the current one. However, the new one has been ported to a completely different compiler and tool-chain which may have introduced new subtle bugs.  The new beta also has numerous bug fixes. This shell needs more rigorous community testing before it replaces the legacy version. 
The new FreeCOM is included on the CD and USB media. Simply install the FreeCOM package. Then edit your FDCONFIG.SYS to point to the new shell. 
When the new Beta FreeCOM replaces the old is not known and mostly depends on community testing and feedback. Of which we have received very little. My 

The FD13-Floppy is an alternate boot method for computers that have a supported CD, but cannot boot from CD. It contains the complete installer and only pulls packages from the CD media. 

FDI-x86 is a completely different installer and uses an entirely different process. At present, it does not do any lang customizations to the installed config and does not prompt for language. This will probably change at some point.

Testing changes, although there may be no RC4. I can probably do a dev only release to allow you and any other translators to review the appearance of your work and make any necessary changes.

**Comment by bitigchi** [comment]
A dev build would be greatly appreciated! Thank you @shidel!

**Comment by shidel** [comment]
@cardpuncher PGME is an behemoth of a complex runtime customizable object-oriented framework. All of it's objects have default settings and some have text. Those default settings, can be overridden in whole or in part by language and/or theme files. Spanish was a fairly easy translation. I speak a little Spanish. So, I created one with my slight knowledge and help from Google translate and created a custom theme for it to account for the different lengths of text. A little while later, some kindly provided a much better translation. 

For languages like TR, RU and etc, it is a little more complicated. Those will also require a font.
Thankfully, that is not hard. Assuming your DOS is configured with the correct codepage and such, you can easily use the included EFONTDSGN program to create one. When you create a font in EFNTDSGN it copies the current system font. Then you can adjust it as needed. You can also change the font height. For example, normally a VGA system has an 8(or 9)x16 font. But, you could load it, stretch it to 8x20, tweak it and have that be your language font. 

Back to PGME themes and languages, things that do not need overridden should be removed from them to permit faster loading. This is why the FD-NLS version of English is basically empty. 

Another thing about the theme and language files, they support a "merge" feature. For example, if most of Europe uses a standard date/time format. It could be placed in its own file. Then any language that uses that could "merge" in those settings. Or, if there were two French translations, like Standard French and French Canadian, one could have only a couple updated strings and merge in the primary other, then merge in date/time settings. Etc.

Oh, did I mention it supports key mappings as well. lol.

Anyhow, I forgot to include the PGME defaults. So, I just added them. 

Here's a minor tip... 

You could clone the defaults to the language you want to do the translations. The switch PGME over to that language and theme. Then add a menu item to run edit on those files. Then launch edit from PGME, make changes, quit, see changes, repeat until done.

Also, some item keys can be multi-line. You can easily identify these. The indented '+=' lines extend the preceding key. These extensions don't have fixed counts. You can add/remove them as needed. And indentation is only for read-ability. 

If you've got any questions... :-)

**Comment by bitigchi** [comment]
@shidel, may I request you to modify the Turkish name for Swiss French and Swiss German as İsviçre Fransızcası ve İsviçre Almancası respectively on your end? I am not sure how to save the encoding on these files, and I don't want to mess up the other languages.

**Comment by bitigchi** [comment]
@cardpuncher, may I request you to review the TR translations for the new fdi-x86 installer? I'm not very well versed on the syntax for the colours here, and I'm afraid I might've messed up something. :)

**Comment by cardpuncher** [comment]
On 2.06.2020 17:58, Emir Sarı wrote:
> @cardpuncher <https://github.com/cardpuncher>, may I request you to
> review the TR translations for the new fdi-x86 installer? I'm not very
> well versed on the syntax for the colours here, and I'm afraid I
> might've messed up something. :)

Hehe, I just finished translating it in French and I used your
translation a lot as a basis for the exact same reason you mentioned. So
all the mistakes I (may) have made are your fault, thank you very much :p

More seriously, shouldn't "kurulumu öntanımla ayarları kullanarak yapar"
be "kurulumu öntanımlı ayarları kullanarak yapar" (öntanımlı instead of
öntanımla)?

And I would suggest "GPL v2.0 Lisansı kapsamında yayımlanmıştır."
instead of "GPL v2.0 Lisansı altında yayımlanmıştır."

If I notice something else, I'll drop you a message.

**Comment by bitigchi** [comment]
@cardpuncher, fixed those two, thanks.

I am just not sure what does /s- stand for. Other than that it should be fine I guess. :)

**Comment by shidel** [comment]
> @cardpuncher, fixed those two, thanks.
> 
> I am just not sure what does /s- stand for. Other than that it should be fine I guess. :)

/s- turns of non-quoted spacing. /s+ turns it pack on.

So:  /s- "Hello there!" how are you? /s+ "I am fine." I think.
would output like:  Hello there!howareyou? I am fine. I think.
Basically, it makes it easier to do multicolor stuff like (something) where parens are different color then "something". 
/p is new line.
/r N is repeat
/c N is ascii value.
Qoute nesting 'hi there "bob"' or "bob's house" etc.

**Comment by bitigchi** [comment]
> So: /s- "Hello there!" how are you? /s+ "I am fine." I think.
> would output like: Hello there!howareyou? I am fine. I think.
> Basically, it makes it easier to do multicolor stuff like (something) where parens are different color then "something".

This is still a bit confusing. The reason I'm worried is, Turkish has complete opposite word ordering compared to English, so strings are generally translated in reverse. Could you please have a look at one or two examples in the new translations, and guide me for the rest?

**Pull request merged**
