### PR TITLE
More packages translated into Swedish.

### PR DESCRIPTION
**Pull request by sebras**

### CODE REVIEW

**Comment by shidel** [comment]
@sebras according to the report generation utility there are a couple minor key errors.

label is missing 1.1, has extra 3.1 key (it appears to by a typo)
runtime is missing key 0.1
sort is missing key 0.2

**Comment by sebras** [comment]
@shidel Yes, I noticed now that I know about the report. :) Sorry about that. I'll get them fixed with the next batch.

**Comment by sebras** [comment]
@shidel BTW, the fact that you merge these translations immediately means that the work I put in feels more useful. Thank you for taking the time to be so responsive. :)

**Comment by shidel** [comment]
@sebras Ok. 
Your welcome. 
:-)

**Pull request merged**
